# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: 主页
    url: /
  archives:
    text: 归档
    url: /archives
  th-list:
    text: 分类
    url: /categories
  tags:
    text: 标签
    url: /tags
  github:
    text: 代码
    url: https://github.com/abelsu7
  book:
    text: 读书
    url: /books
  film:
    text: 影视
    url: /movies
  gamepad:
    text: 游戏
    url: /games
  info-circle:
    text: 关于
    url: /about

# 你的头像url
avatar: /img/fong.jpg
# avatar link
avatar_link: /
# 头像背景图
brand: /img/back_blue.png
# favicon
favicon: /img/favicon.ico

# email
email: abelsu7@gmail.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#3F51B5'

# 页面标题
tags_title: Tags
archives_title: Archives
categories_title: Categories

# 文章截断
excerpt_render: true
excerpt_length: 200
excerpt_link: 阅读全文...
mathjax: true
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: true

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward:
  title: 感谢支持！
  wechat: /img/wechat.png     #微信，关闭设为 false
  alipay: /img/alipay.jpg     #支付宝，关闭设为 false

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: true

# 是否开启toc
# toc: false
toc:
  list_number: false  # 是否显示数字排序

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage: 文章发布地址：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.permalink.replace(/index\.html$/, '') %></a>

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# 百度统计，如要开启，改为你的 key
baidu_tongji: c61262c25ca5d4ed66df331a31b5bf49

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: false
google_site_verification: false

# sogou站长验证 http://zhanzhang.sogou.com/
sogou_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# 以下评论插件开启一个即可
# 是否开启 disqus
disqus_shortname: false
# 是否开启友言评论, 填写友言用户id
uyan_uid: false
# 是否使用 gitment，https://github.com/imsun/gitment
gitment: false
# gitment:
#   owner:
#   repo:
#   client_id:
#   client_secret:

# use gitalk://github.com/gitalk/gitalk
gitalk: false
#  owner: 
#  repo: 
#  client_id: 
#  client_secret: 

# Valine Comment system. https://valine.js.org
valine:
  enable: false # 如果你想使用 Valine，请将值设置为 true
  appId:  # your leancloud appId
  appKey: # your leancloud appKey
  notify: false # Mail notify
  verify: false # Verify code
  avatar: mp # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: 'Write a comment' # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size

# 是否开启 Hyper Comments，填写 id 则启用，false 则禁用。http://hypercomments.com
# Hyper Comments support. Write your id here, or false to disable
hyper_id: false

# 畅言
changyan:
  enable: false
  appid: # your changyan appid
  appkey: # your changyan appkey

# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: false

# 版权起始年份
since_year: 2018

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: 用户页面中作者相关的描述性文字，如不需要设为 false

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: 站点总访客数：
  site_pv: 站点总访问量：

# 动态定义 title
# title_change:
#  normal: (つェ⊂)咦!又好了!
#  leave: 死鬼去哪里了！

# 设置为 true 发布后将使用 unpkg cdn 最新的主题样式
# 如果想让你的自定义样式生效，把此项设为 false
cdn: false

# 设置为 true 将使用 lightbox render 图片
lightbox: true

# icp备案号  ICP_license: 京ICP备1234556号-1
ICP_license: false

# Prism Theme, default/coy/okaidia/atom-dark/solarized-light/tomorrow-night
prism:
  theme: tomorrow-night